Integrations
SematP/SkillsFrontend pull request #12
Opened 2022-04-27 08:19 UTC by semat-skills

2022-04-27 14:22 UTC, NirK8 requested changes
Good job Semat! Please note that the handler method only receives the arguments it needs.
The controller is responsible for responding the client.

2022-04-27 14:22 UTC, NirK8 commented on backend/src/controllers/user.ts
> +    handleSignup(req, res);
Like we said in our conversation this morning, to the handler you don't pass the `req` and `res` objects, but only the parameters which the handler method needs.

2022-05-01 06:57 UTC, NirK8 requested changes
Changes requested

2022-05-01 06:57 UTC, NirK8 commented on backend/src/handlers/contact.ts
> +      img: img,
Instead of passing the whole request object to the handler, just pass it with the needed arguments (fullname, email, etc.)

2022-05-01 06:57 UTC, NirK8 commented on backend/src/controllers/user.ts
> +    handleUpdatePassword(req, res);
>     handleUpdatePassword(req, res);

No need to pass req & res to the handler.
Pass only the necessary arguments to the handler

2022-05-01 06:57 UTC, NirK8 commented on backend/src/handlers/hike.ts
> +      text: req.body.text,
Same here, pass only needed arguments to the handler. Please speak with Lior about this :)

2022-05-01 08:12 UTC, semat-skills reviewed
changes

2022-05-01 08:12 UTC, SematP commented on backend/src/controllers/contact.ts
> +      req.body.searchFor
destruct

2022-05-01 08:12 UTC, SematP commented on backend/src/controllers/hike.ts
> +      req.body.text
destruct

2022-05-01 08:12 UTC, SematP commented on backend/src/controllers/user.ts
> +      req.body.password
destruct

2022-05-01 08:12 UTC, SematP commented on backend/src/handlers/contact.ts
> +      img: img,
destruct

2022-05-01 08:12 UTC, SematP commented on backend/src/handlers/hike.ts
> +      text: text,
destruct

2022-05-01 08:12 UTC, SematP commented on backend/src/handlers/user.ts
> +        fullname: fullname,
destruct

2022-05-01 08:12 UTC, SematP commented on backend/src/controllers/user.ts
> +      res.send(result.msg);
error handling

2022-05-01 08:12 UTC, SematP commented on backend/src/routes/contact.ts
> +router.use(bodyParser.json());
> router.use(bodyParser.json());

Move to app

2022-05-01 08:12 UTC, SematP commented on frontend/src/Assets/styles/globalStyle.ts
> +import px2vw from "../styles/px2vw";
change to rem

2022-05-01 08:12 UTC, SematP commented on frontend/src/Components/Form/FormikContact.tsx
> +  baseURL: "http://localhost:3000/contact",
move to package.json

2022-05-01 08:12 UTC, semat-skills commented on backend/src/handlers/slack.ts
> +    //  res.status(400);
handle error

2022-05-01 08:12 UTC, semat-skills commented on frontend/src/Pages/ContactPage/ContactPage.tsx
> +interface ContactPageProps {}
remove empty type

2022-05-02 12:12 UTC, NirK8 approved these changes

2022-05-02 12:17 UTC, merged